version: "3.9"
services: 
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    container_name: test_postgres
    image: postgres  
    environment:  
      - POSTGRES_USER=test_postgres  
      - POSTGRES_PASSWORD=test_postgres  
      - POSTGRES_DB=test_postgres
    ports:  
      - "5432:5432"